/* soal.js
   STDA4101 — Pengantar Sains Data
   50 Soal Lengkap + Simulasi
*/

window.QUESTION_BANK = [
    {
        id: "q1",
        question: "Dataset pendapatan (juta rupiah): 2, 2, 3, 3, 4, 4, 100. Ukuran pemusatan data yang PALING tepat untuk menggambarkan kondisi mayoritas responden adalah …",
        choices: [
            { id: "A", text: "Mean" },
            { id: "B", text: "Median" },
            { id: "C", text: "Modus" },
            { id: "D", text: "Range" },
        ],
        answerId: "B",
        explanation: "Terdapat outlier ekstrem (100) yang membuat mean bias. Median lebih merepresentasikan mayoritas data.",
        points: 2,
    },
    {
        id: "q2",
        question: "Jika suatu distribusi memiliki mean > median > modus, maka bentuk distribusinya adalah …",
        choices: [
            { id: "A", text: "Simetris" },
            { id: "B", text: "Miring ke kiri" },
            { id: "C", text: "Miring ke kanan" },
            { id: "D", text: "Bimodal" },
        ],
        answerId: "C",
        explanation: "Mean tertarik ke ekor panjang di kanan (skewed right).",
        points: 2,
    },
    {
        id: "q3",
        question: "Standar deviasi digunakan untuk mengukur …",
        choices: [
            { id: "A", text: "Nilai tengah data" },
            { id: "B", text: "Frekuensi data" },
            { id: "C", text: "Penyebaran data terhadap mean" },
            { id: "D", text: "Hubungan antar variabel" },
        ],
        answerId: "C",
        explanation: "Standar deviasi menunjukkan seberapa jauh data menyebar dari rata-rata.",
        points: 2,
    },
    {
        id: "q4",
        question: "Jika seluruh nilai dalam dataset ditambah konstanta yang sama, maka standar deviasi akan …",
        choices: [
            { id: "A", text: "Bertambah" },
            { id: "B", text: "Berkurang" },
            { id: "C", text: "Tetap" },
            { id: "D", text: "Menjadi nol" },
        ],
        answerId: "C",
        explanation: "Penambahan konstanta tidak mengubah sebaran data.",
        points: 2,
    },
    {
        id: "q5",
        question: "Ukuran penyebaran yang PALING sensitif terhadap outlier adalah …",
        choices: [
            { id: "A", text: "Median" },
            { id: "B", text: "IQR" },
            { id: "C", text: "Varians" },
            { id: "D", text: "Modus" },
        ],
        answerId: "C",
        explanation: "Varians dan standar deviasi sangat sensitif terhadap pencilan.",
        points: 2,
    },
    {
        id: "q6",
        question: "Diagram yang PALING tepat untuk menampilkan proporsi kategori adalah …",
        choices: [
            { id: "A", text: "Histogram" },
            { id: "B", text: "Scatter plot" },
            { id: "C", text: "Diagram lingkaran" },
            { id: "D", text: "Grafik garis" },
        ],
        answerId: "C",
        explanation: "Diagram lingkaran menunjukkan proporsi bagian terhadap keseluruhan.",
        points: 2,
    },
    {
        id: "q7",
        question: "Data yang memiliki nol absolut termasuk dalam skala …",
        choices: [
            { id: "A", text: "Nominal" },
            { id: "B", text: "Ordinal" },
            { id: "C", text: "Interval" },
            { id: "D", text: "Rasio" },
        ],
        answerId: "D",
        explanation: "Skala rasio memiliki nol mutlak (contoh: berat badan).",
        points: 2,
    },
    {
        id: "q8",
        question: "Range dihitung dengan cara …",
        choices: [
            { id: "A", text: "Mean − median" },
            { id: "B", text: "Nilai terbesar − nilai terkecil" },
            { id: "C", text: "Varians × standar deviasi" },
            { id: "D", text: "Jumlah data ÷ frekuensi" },
        ],
        answerId: "B",
        explanation: "Range adalah selisih nilai maksimum dan minimum.",
        points: 2,
    },
    {
        id: "q9",
        question: "Modus PALING berguna ketika …",
        choices: [
            { id: "A", text: "Data simetris sempurna" },
            { id: "B", text: "Data kategorik" },
            { id: "C", text: "Data memiliki outlier" },
            { id: "D", text: "Data kontinu" },
        ],
        answerId: "B",
        explanation: "Modus cocok untuk data kategorik atau frekuensi tertinggi.",
        points: 2,
    },
    {
        id: "q10",
        question: "Histogram TIDAK dapat digunakan untuk …",
        choices: [
            { id: "A", text: "Melihat distribusi" },
            { id: "B", text: "Melihat sebaran" },
            { id: "C", text: "Menentukan hubungan sebab akibat" },
            { id: "D", text: "Mengidentifikasi skewness" },
        ],
        answerId: "C",
        explanation: "Histogram tidak menunjukkan kausalitas.",
        points: 2,
    },

    /* ================= ANALISIS & KORELASI (16–30) ================= */

    {
        id: "q16",
        question: "Scatter plot menunjukkan pola naik dari kiri ke kanan. Kesimpulan PALING tepat adalah …",
        choices: [
            { id: "A", text: "Hubungan sebab-akibat pasti" },
            { id: "B", text: "Korelasi positif" },
            { id: "C", text: "Korelasi negatif" },
            { id: "D", text: "Tidak ada hubungan" },
        ],
        answerId: "B",
        explanation: "Pola naik menunjukkan korelasi positif, bukan kausalitas.",
        points: 2,
    },
    {
        id: "q17",
        question: "Nilai korelasi sebesar -0,85 menunjukkan …",
        choices: [
            { id: "A", text: "Hubungan lemah" },
            { id: "B", text: "Hubungan kuat negatif" },
            { id: "C", text: "Hubungan kuat positif" },
            { id: "D", text: "Tidak ada hubungan" },
        ],
        answerId: "B",
        explanation: "Nilai mendekati -1 berarti hubungan negatif yang kuat.",
        points: 2,
    },
    {
        id: "q18",
        question: "Korelasi bernilai nol berarti …",
        choices: [
            { id: "A", text: "Tidak ada hubungan sama sekali" },
            { id: "B", text: "Tidak ada hubungan linear" },
            { id: "C", text: "Data salah" },
            { id: "D", text: "Hubungan sebab akibat" },
        ],
        answerId: "B",
        explanation: "Masih mungkin ada hubungan non-linear.",
        points: 2,
    },
    {
        id: "q19",
        question: "Variabel yang dipengaruhi oleh variabel lain disebut …",
        choices: [
            { id: "A", text: "Variabel bebas" },
            { id: "B", text: "Variabel perancu" },
            { id: "C", text: "Variabel terikat" },
            { id: "D", text: "Variabel acak" },
        ],
        answerId: "C",
        explanation: "Variabel terikat (Y) dipengaruhi variabel bebas (X).",
        points: 2,
    },
    {
        id: "q20",
        question: "Pernyataan yang PALING benar tentang korelasi adalah …",
        choices: [
            { id: "A", text: "Korelasi selalu berarti sebab-akibat" },
            { id: "B", text: "Korelasi tidak pernah berguna" },
            { id: "C", text: "Korelasi menunjukkan arah dan kekuatan hubungan" },
            { id: "D", text: "Korelasi hanya untuk data kategorik" },
        ],
        answerId: "C",
        explanation: "Ini jebakan klasik UT.",
        points: 2,
    },
    {
        id: "q21",
        question: "Variabel perancu adalah variabel yang …",
        choices: [
            { id: "A", text: "Tidak penting" },
            { id: "B", text: "Mempengaruhi hubungan X dan Y" },
            { id: "C", text: "Selalu konstan" },
            { id: "D", text: "Tidak bisa diukur" },
        ],
        answerId: "B",
        explanation: "Confounding variable memengaruhi interpretasi hubungan.",
        points: 2,
    },
    {
        id: "q22",
        question: "Hubungan jam belajar dan nilai ujian termasuk analisis …",
        choices: [
            { id: "A", text: "Univariat" },
            { id: "B", text: "Bivariat" },
            { id: "C", text: "Multivariat" },
            { id: "D", text: "Nominal" },
        ],
        answerId: "B",
        explanation: "Melibatkan dua variabel.",
        points: 2,
    },
    {
        id: "q23",
        question: "Jika scatter plot menyebar acak tanpa pola, maka …",
        choices: [
            { id: "A", text: "Korelasi kuat" },
            { id: "B", text: "Korelasi negatif" },
            { id: "C", text: "Tidak ada korelasi" },
            { id: "D", text: "Hubungan kausal" },
        ],
        answerId: "C",
        explanation: "Tidak ada hubungan yang jelas.",
        points: 2,
    },
    {
        id: "q24",
        question: "Grafik PALING tepat untuk melihat tren waktu adalah …",
        choices: [
            { id: "A", text: "Histogram" },
            { id: "B", text: "Diagram lingkaran" },
            { id: "C", text: "Grafik garis" },
            { id: "D", text: "Scatter plot" },
        ],
        answerId: "C",
        explanation: "Time series cocok dengan grafik garis.",
        points: 2,
    },
    {
        id: "q25",
        question: "Analisis deskriptif dilakukan sebelum inferensial karena …",
        choices: [
            { id: "A", text: "Lebih sulit" },
            { id: "B", text: "Untuk memahami karakteristik awal data" },
            { id: "C", text: "Lebih mahal" },
            { id: "D", text: "Wajib statistik" },
        ],
        answerId: "B",
        explanation: "Deskriptif memberi gambaran awal.",
        points: 2,
    },

    /* ================= STUDI KASUS & JEBATAN UT (31–50) ================= */

    {
        id: "q31",
        question: "Korelasi tinggi antara penjualan es krim dan jumlah orang tenggelam PALING tepat disimpulkan sebagai …",
        choices: [
            { id: "A", text: "Es krim menyebabkan tenggelam" },
            { id: "B", text: "Tenggelam meningkatkan penjualan es krim" },
            { id: "C", text: "Dipengaruhi variabel lain (musim)" },
            { id: "D", text: "Kesalahan data" },
        ],
        answerId: "C",
        explanation: "Musim panas memengaruhi keduanya.",
        points: 2,
    },
    {
        id: "q32",
        question: "Mean PALING cocok digunakan jika distribusi data …",
        choices: [
            { id: "A", text: "Banyak outlier" },
            { id: "B", text: "Simetris" },
            { id: "C", text: "Ordinal" },
            { id: "D", text: "Kategori" },
        ],
        answerId: "B",
        explanation: "Mean optimal pada distribusi simetris.",
        points: 2,
    },
    {
        id: "q33",
        question: "Median > mean menunjukkan distribusi …",
        choices: [
            { id: "A", text: "Miring kanan" },
            { id: "B", text: "Miring kiri" },
            { id: "C", text: "Simetris" },
            { id: "D", text: "Normal" },
        ],
        answerId: "B",
        explanation: "Distribusi skewed left.",
        points: 2,
    },
    {
        id: "q34",
        question: "Tujuan utama eksplorasi data adalah …",
        choices: [
            { id: "A", text: "Prediksi langsung" },
            { id: "B", text: "Menemukan pola dan anomali" },
            { id: "C", text: "Uji hipotesis" },
            { id: "D", text: "Evaluasi model" },
        ],
        answerId: "B",
        explanation: "EDA fokus pada pemahaman awal data.",
        points: 2,
    },
    {
        id: "q35",
        question: "Bias data PALING mungkin terjadi jika …",
        choices: [
            { id: "A", text: "Data besar" },
            { id: "B", text: "Data tidak representatif" },
            { id: "C", text: "Data numerik" },
            { id: "D", text: "Data bersih" },
        ],
        answerId: "B",
        explanation: "Bias berasal dari sampel tidak mewakili populasi.",
        points: 2,
    },
    {
        id: "q36",
        question: "Overfitting berarti …",
        choices: [
            { id: "A", text: "Model terlalu sederhana" },
            { id: "B", text: "Model terlalu mengikuti data latih" },
            { id: "C", text: "Model tanpa data" },
            { id: "D", text: "Model acak" },
        ],
        answerId: "B",
        explanation: "Model tidak mampu generalisasi.",
        points: 2,
    },
    {
        id: "q37",
        question: "Cara mengurangi overfitting yang PALING tepat adalah …",
        choices: [
            { id: "A", text: "Menambah kompleksitas model" },
            { id: "B", text: "Menghapus data uji" },
            { id: "C", text: "Regularisasi dan validasi silang" },
            { id: "D", text: "Menggunakan seluruh data" },
        ],
        answerId: "C",
        explanation: "Teknik umum dalam machine learning.",
        points: 2,
    },
    {
        id: "q38",
        question: "Kesalahan interpretasi data sering terjadi karena …",
        choices: [
            { id: "A", text: "Data sedikit" },
            { id: "B", text: "Analisis tanpa konteks" },
            { id: "C", text: "Visualisasi baik" },
            { id: "D", text: "Data bersih" },
        ],
        answerId: "B",
        explanation: "Konteks sangat penting.",
        points: 2,
    },
    {
        id: "q39",
        question: "Etika data berkaitan erat dengan …",
        choices: [
            { id: "A", text: "Kecepatan komputasi" },
            { id: "B", text: "Privasi dan keamanan data" },
            { id: "C", text: "Jumlah data" },
            { id: "D", text: "Grafik" },
        ],
        answerId: "B",
        explanation: "Isu utama etika data.",
        points: 2,
    },
    {
        id: "q40",
        question: "Kesimpulan PALING aman dari korelasi tinggi adalah …",
        choices: [
            { id: "A", text: "Hubungan sebab akibat" },
            { id: "B", text: "Hubungan kuat" },
            { id: "C", text: "Prediksi pasti" },
            { id: "D", text: "Data salah" },
        ],
        answerId: "B",
        explanation: "UT sangat sering pakai kesimpulan ini.",
        points: 2,
    },

    /* === AI & MASA DEPAN === */
    {
        id: "q41",
        question: "Artificial Intelligence (AI) adalah …",
        choices: [
            { id: "A", text: "Komputer biasa" },
            { id: "B", text: "Sistem yang meniru kecerdasan manusia" },
            { id: "C", text: "Basis data" },
            { id: "D", text: "Program statis" },
        ],
        answerId: "B",
        explanation: "AI meniru kecerdasan manusia.",
        points: 2,
    },
    {
        id: "q42",
        question: "Machine learning memungkinkan sistem untuk …",
        choices: [
            { id: "A", text: "Berjalan tanpa data" },
            { id: "B", text: "Belajar dari data" },
            { id: "C", text: "Menghapus data" },
            { id: "D", text: "Menebak acak" },
        ],
        answerId: "B",
        explanation: "Machine learning belajar dari data.",
        points: 2,
    },
    {
        id: "q43",
        question: "Big data ditandai dengan …",
        choices: [
            { id: "A", text: "Data kecil" },
            { id: "B", text: "Volume, Velocity, Variety" },
            { id: "C", text: "Satu jenis data" },
            { id: "D", text: "Data manual" },
        ],
        answerId: "B",
        explanation: "Big data dikenal dengan 3V.",
        points: 2,
    },
    {
        id: "q44",
        question: "Salah satu tantangan sains data adalah …",
        choices: [
            { id: "A", text: "Data selalu bersih" },
            { id: "B", text: "Kualitas data" },
            { id: "C", text: "Data sedikit" },
            { id: "D", text: "Tidak ada bias" },
        ],
        answerId: "B",
        explanation: "Kualitas data sangat menentukan hasil.",
        points: 2,
    },
    {
        id: "q45",
        question: "Peran data scientist adalah …",
        choices: [
            { id: "A", text: "Mengetik laporan" },
            { id: "B", text: "Mengubah data menjadi insight" },
            { id: "C", text: "Menghapus database" },
            { id: "D", text: "Menggambar grafik saja" },
        ],
        answerId: "B",
        explanation: "Data scientist menghasilkan insight dari data.",
        points: 2,
    },
    {
        id: "q46",
        question: "Clean data berarti …",
        choices: [
            { id: "A", text: "Data baru" },
            { id: "B", text: "Data bebas kesalahan" },
            { id: "C", text: "Data sedikit" },
            { id: "D", text: "Data rahasia" },
        ],
        answerId: "B",
        explanation: "Clean data minim kesalahan.",
        points: 2,
    },
    {
        id: "q47",
        question: "Missing value berarti …",
        choices: [
            { id: "A", text: "Nilai salah" },
            { id: "B", text: "Nilai hilang" },
            { id: "C", text: "Nilai duplikat" },
            { id: "D", text: "Nilai ekstrem" },
        ],
        answerId: "B",
        explanation: "Missing value adalah nilai yang tidak ada.",
        points: 2,
    },
    {
        id: "q48",
        question: "Handling missing value dapat dilakukan dengan …",
        choices: [
            { id: "A", text: "Mengabaikan semua data" },
            { id: "B", text: "Mengisi atau menghapus" },
            { id: "C", text: "Menambah noise" },
            { id: "D", text: "Menggandakan data" },
        ],
        answerId: "B",
        explanation: "Missing value bisa dihapus atau diimputasi.",
        points: 2,
    },
    {
        id: "q49",
        question: "Insight dalam sains data berarti …",
        choices: [
            { id: "A", text: "Data mentah" },
            { id: "B", text: "Informasi bermakna" },
            { id: "C", text: "Angka acak" },
            { id: "D", text: "Error data" },
        ],
        answerId: "B",
        explanation: "Insight adalah informasi bernilai.",
        points: 2,
    },
    {
        id: "q50",
        question: "Kesimpulan utama dari sains data adalah …",
        choices: [
            { id: "A", text: "Data selalu benar" },
            { id: "B", text: "Data harus dianalisis dengan etika dan konteks" },
            { id: "C", text: "Semua prediksi akurat" },
            { id: "D", text: "AI menggantikan manusia sepenuhnya" },
        ],
        answerId: "B",
        explanation: "Sains data harus mempertimbangkan konteks dan etika.",
        points: 2,
    },
];

window.SIMULATION_BANK = window.QUESTION_BANK.slice(0, 10);