// asset/soal.js
// QUESTION_BANK untuk Tata Kelola Teknologi Informasi (STSI4402)
// 50 soal x 2 poin = total 100 poin
window.QUESTION_BANK = [
    {
        id: "t1",
        question: "Tata kelola Teknologi Informasi (TI) adalah …",
        choices: [
            { id: "A", text: "Pengelolaan perangkat keras" },
            {
                id: "B",
                text: "Sistem untuk memastikan TI mendukung tujuan organisasi",
            },
            { id: "C", text: "Kegiatan teknis harian" },
            { id: "D", text: "Pengembangan aplikasi" },
        ],
        answerId: "B",
        explanation:
            "Tata kelola TI memastikan keselarasan TI dengan tujuan bisnis.",
        points: 2,
    },
    {
        id: "t2",
        question: "Tujuan utama tata kelola TI adalah …",
        choices: [
            { id: "A", text: "Mengurangi penggunaan TI" },
            { id: "B", text: "Menciptakan nilai bisnis dari TI" },
            { id: "C", text: "Menambah biaya operasional" },
            { id: "D", text: "Menghilangkan risiko sepenuhnya" },
        ],
        answerId: "B",
        explanation: "Governance TI berfokus pada penciptaan nilai bisnis.",
        points: 2,
    },
    {
        id: "t3",
        question: "Perbedaan utama tata kelola TI dan manajemen TI adalah …",
        choices: [
            { id: "A", text: "Governance strategis, manajemen operasional" },
            { id: "B", text: "Governance lebih teknis" },
            { id: "C", text: "Manajemen tidak penting" },
            { id: "D", text: "Keduanya sama" },
        ],
        answerId: "A",
        explanation: "Governance menentukan arah, manajemen mengeksekusi.",
        points: 2,
    },
    {
        id: "t4",
        question: "Pihak yang bertanggung jawab atas tata kelola TI adalah …",
        choices: [
            { id: "A", text: "Staf IT" },
            { id: "B", text: "Manajemen puncak" },
            { id: "C", text: "Programmer" },
            { id: "D", text: "Operator sistem" },
        ],
        answerId: "B",
        explanation: "Tata kelola TI adalah tanggung jawab manajemen puncak.",
        points: 2,
    },
    {
        id: "t5",
        question: "Prinsip utama tata kelola TI adalah …",
        choices: [
            { id: "A", text: "Teknologi terbaru" },
            { id: "B", text: "Keselarasan TI dan bisnis" },
            { id: "C", text: "Biaya rendah" },
            { id: "D", text: "Kecepatan sistem" },
        ],
        answerId: "B",
        explanation: "Alignment TI–bisnis adalah inti governance.",
        points: 2,
    },
    {
        id: "t6",
        question: "Tata kelola TI berfokus pada …",
        choices: [
            { id: "A", text: "Kontrol dan arah TI" },
            { id: "B", text: "Pemrograman" },
            { id: "C", text: "Maintenance server" },
            { id: "D", text: "Troubleshooting" },
        ],
        answerId: "A",
        explanation: "Governance mengatur arah dan kontrol TI.",
        points: 2,
    },
    {
        id: "t7",
        question: "Manajemen TI bertugas untuk …",
        choices: [
            { id: "A", text: "Menentukan strategi bisnis" },
            { id: "B", text: "Menjalankan dan mengelola TI" },
            { id: "C", text: "Menetapkan kebijakan nasional" },
            { id: "D", text: "Audit eksternal" },
        ],
        answerId: "B",
        explanation: "Manajemen TI mengeksekusi strategi.",
        points: 2,
    },
    {
        id: "t8",
        question: "Tata kelola TI yang baik harus bersifat …",
        choices: [
            { id: "A", text: "Teknis saja" },
            { id: "B", text: "Terstruktur dan terkontrol" },
            { id: "C", text: "Tidak terdokumentasi" },
            { id: "D", text: "Fleksibel tanpa aturan" },
        ],
        answerId: "B",
        explanation: "Governance memerlukan struktur dan kontrol.",
        points: 2,
    },
    {
        id: "t9",
        question: "Nilai bisnis dari TI disebut juga …",
        choices: [
            { id: "A", text: "Cost center" },
            { id: "B", text: "Value creation" },
            { id: "C", text: "Maintenance" },
            { id: "D", text: "Overhead" },
        ],
        answerId: "B",
        explanation: "TI harus menciptakan nilai bisnis.",
        points: 2,
    },
    {
        id: "t10",
        question: "Tata kelola TI TIDAK bertujuan untuk …",
        choices: [
            { id: "A", text: "Mendukung tujuan organisasi" },
            { id: "B", text: "Mengendalikan risiko" },
            { id: "C", text: "Menghilangkan seluruh risiko" },
            { id: "D", text: "Menciptakan nilai" },
        ],
        answerId: "C",
        explanation: "Risiko tidak dihilangkan, tapi dikelola.",
        points: 2,
    },

    /* ===== 11–20 : FRAMEWORK ===== */
    {
        id: "t11",
        question: "COBIT merupakan framework untuk …",
        choices: [
            { id: "A", text: "Manajemen proyek" },
            { id: "B", text: "Tata kelola dan manajemen TI" },
            { id: "C", text: "Keamanan jaringan" },
            { id: "D", text: "Pemrograman" },
        ],
        answerId: "B",
        explanation: "COBIT fokus pada governance dan management TI.",
        points: 2,
    },
    {
        id: "t12",
        question: "ITIL berfokus pada …",
        choices: [
            { id: "A", text: "Audit TI" },
            { id: "B", text: "Manajemen layanan TI" },
            { id: "C", text: "Keamanan informasi" },
            { id: "D", text: "Strategi bisnis" },
        ],
        answerId: "B",
        explanation: "ITIL adalah best practice ITSM.",
        points: 2,
    },
    {
        id: "t13",
        question: "ISO/IEC 38500 mengatur tentang …",
        choices: [
            { id: "A", text: "Keamanan informasi" },
            { id: "B", text: "Tata kelola TI organisasi" },
            { id: "C", text: "Manajemen risiko" },
            { id: "D", text: "Audit keuangan" },
        ],
        answerId: "B",
        explanation: "ISO 38500 adalah standar governance TI.",
        points: 2,
    },
    {
        id: "t14",
        question: "Framework yang kuat pada kontrol internal adalah …",
        choices: [
            { id: "A", text: "ITIL" },
            { id: "B", text: "COBIT" },
            { id: "C", text: "Scrum" },
            { id: "D", text: "XP" },
        ],
        answerId: "B",
        explanation: "COBIT menekankan kontrol dan audit.",
        points: 2,
    },
    {
        id: "t15",
        question: "Tujuan penggunaan framework TI adalah …",
        choices: [
            { id: "A", text: "Menghilangkan risiko" },
            { id: "B", text: "Memberi panduan best practice" },
            { id: "C", text: "Menggantikan manajemen" },
            { id: "D", text: "Menambah birokrasi" },
        ],
        answerId: "B",
        explanation: "Framework memberi panduan terstruktur.",
        points: 2,
    },
    {
        id: "t16",
        question: "COBIT membantu organisasi dalam …",
        choices: [
            { id: "A", text: "Pemrograman" },
            { id: "B", text: "Pengambilan keputusan TI" },
            { id: "C", text: "Desain UI" },
            { id: "D", text: "Coding backend" },
        ],
        answerId: "B",
        explanation: "COBIT membantu decision making TI.",
        points: 2,
    },
    {
        id: "t17",
        question: "ITIL paling tepat digunakan pada …",
        choices: [
            { id: "A", text: "Pengembangan startup" },
            { id: "B", text: "Manajemen layanan TI" },
            { id: "C", text: "Audit keuangan" },
            { id: "D", text: "AI research" },
        ],
        answerId: "B",
        explanation: "ITIL fokus pada layanan TI.",
        points: 2,
    },
    {
        id: "t18",
        question: "Framework tata kelola TI membantu organisasi agar …",
        choices: [
            { id: "A", text: "TI berjalan tanpa aturan" },
            { id: "B", text: "TI selaras dengan bisnis" },
            { id: "C", text: "TI terpisah dari bisnis" },
            { id: "D", text: "TI bersifat eksperimental" },
        ],
        answerId: "B",
        explanation: "Alignment adalah tujuan utama.",
        points: 2,
    },
    {
        id: "t19",
        question: "Framework TIDAK digunakan untuk …",
        choices: [
            { id: "A", text: "Panduan pengelolaan TI" },
            { id: "B", text: "Best practice" },
            { id: "C", text: "Menghapus peran manajemen" },
            { id: "D", text: "Kontrol TI" },
        ],
        answerId: "C",
        explanation: "Framework tidak menggantikan manajemen.",
        points: 2,
    },
    {
        id: "t20",
        question: "Framework tata kelola TI bersifat …",
        choices: [
            { id: "A", text: "Kaku dan mutlak" },
            { id: "B", text: "Dapat disesuaikan dengan organisasi" },
            { id: "C", text: "Hanya untuk perusahaan besar" },
            { id: "D", text: "Teknis murni" },
        ],
        answerId: "B",
        explanation: "Framework bersifat adaptable.",
        points: 2,
    },

    /* ===== 21–30 : RISIKO & KONTROL ===== */
    {
        id: "t21",
        question: "Risiko TI adalah …",
        choices: [
            { id: "A", text: "Kesalahan kecil" },
            { id: "B", text: "Potensi kejadian merugikan organisasi" },
            { id: "C", text: "Kerusakan hardware" },
            { id: "D", text: "Bug software" },
        ],
        answerId: "B",
        explanation: "Risiko berkaitan dengan ketidakpastian.",
        points: 2,
    },
    {
        id: "t22",
        question: "Manajemen risiko TI bertujuan untuk …",
        choices: [
            { id: "A", text: "Menghilangkan risiko" },
            { id: "B", text: "Mengidentifikasi dan mengendalikan risiko" },
            { id: "C", text: "Mengabaikan risiko" },
            { id: "D", text: "Menambah risiko" },
        ],
        answerId: "B",
        explanation: "Risiko dikendalikan, bukan dihapus.",
        points: 2,
    },
    {
        id: "t23",
        question: "Kontrol TI diperlukan untuk …",
        choices: [
            { id: "A", text: "Menambah kecepatan" },
            { id: "B", text: "Menjamin keamanan dan keandalan" },
            { id: "C", text: "Mengurangi SDM" },
            { id: "D", text: "Menambah biaya" },
        ],
        answerId: "B",
        explanation: "Kontrol menjaga sistem tetap andal.",
        points: 2,
    },
    {
        id: "t24",
        question: "CIA Triad terdiri dari …",
        choices: [
            { id: "A", text: "Confidentiality, Integrity, Availability" },
            { id: "B", text: "Control, IT, Audit" },
            { id: "C", text: "Cost, Innovation, Agility" },
            { id: "D", text: "Compliance, Integrity, Audit" },
        ],
        answerId: "A",
        explanation: "CIA adalah dasar keamanan informasi.",
        points: 2,
    },
    {
        id: "t25",
        question: "Audit TI dilakukan untuk …",
        choices: [
            { id: "A", text: "Coding" },
            { id: "B", text: "Menilai efektivitas kontrol TI" },
            { id: "C", text: "Upgrade server" },
            { id: "D", text: "Menambah lisensi" },
        ],
        answerId: "B",
        explanation: "Audit menilai kepatuhan dan efektivitas.",
        points: 2,
    },

    /* ===== 31–40 : STRATEGI & KINERJA ===== */
    {
        id: "t26",
        question: "Value delivery berarti …",
        choices: [
            { id: "A", text: "TI sebagai biaya" },
            { id: "B", text: "TI memberikan manfaat bisnis" },
            { id: "C", text: "TI bersifat teknis" },
            { id: "D", text: "TI tidak penting" },
        ],
        answerId: "B",
        explanation: "TI harus memberi nilai bisnis.",
        points: 2,
    },
    {
        id: "t27",
        question: "KPI digunakan untuk …",
        choices: [
            { id: "A", text: "Menentukan gaji" },
            { id: "B", text: "Mengukur kinerja TI" },
            { id: "C", text: "Menghapus proses" },
            { id: "D", text: "Menambah risiko" },
        ],
        answerId: "B",
        explanation: "KPI mengukur performa.",
        points: 2,
    },
    {
        id: "t28",
        question: "Keselarasan TI dan bisnis berarti …",
        choices: [
            { id: "A", text: "TI berjalan sendiri" },
            { id: "B", text: "TI mendukung tujuan bisnis" },
            { id: "C", text: "Bisnis mengikuti TI" },
            { id: "D", text: "TI tidak dibutuhkan" },
        ],
        answerId: "B",
        explanation: "Alignment adalah inti governance.",
        points: 2,
    },
    {
        id: "t29",
        question: "Portofolio TI digunakan untuk …",
        choices: [
            { id: "A", text: "Menghapus proyek" },
            { id: "B", text: "Mengelola investasi TI" },
            { id: "C", text: "Menambah risiko" },
            { id: "D", text: "Mengganti vendor" },
        ],
        answerId: "B",
        explanation: "Portofolio membantu prioritas investasi.",
        points: 2,
    },
    {
        id: "t30",
        question: "Balanced Scorecard digunakan untuk …",
        choices: [
            { id: "A", text: "Audit keuangan" },
            { id: "B", text: "Mengukur kinerja dari berbagai perspektif" },
            { id: "C", text: "Manajemen proyek" },
            { id: "D", text: "Keamanan jaringan" },
        ],
        answerId: "B",
        explanation: "BSC memberi pandangan menyeluruh.",
        points: 2,
    },

    /* ===== 41–50 : ETIKA & KESIMPULAN ===== */
    {
        id: "t31",
        question: "Etika TI berkaitan dengan …",
        choices: [
            { id: "A", text: "Kecepatan sistem" },
            { id: "B", text: "Tanggung jawab dan kepatuhan" },
            { id: "C", text: "Teknologi baru" },
            { id: "D", text: "Jumlah server" },
        ],
        answerId: "B",
        explanation: "Etika menjaga kepercayaan.",
        points: 2,
    },
    {
        id: "t32",
        question: "Compliance berarti …",
        choices: [
            { id: "A", text: "Mengabaikan aturan" },
            { id: "B", text: "Mematuhi regulasi dan kebijakan" },
            { id: "C", text: "Mengurangi kontrol" },
            { id: "D", text: "Fokus teknis" },
        ],
        answerId: "B",
        explanation: "Compliance adalah bagian governance.",
        points: 2,
    },
    {
        id: "t33",
        question: "Peran SDM dalam tata kelola TI adalah …",
        choices: [
            { id: "A", text: "Tidak penting" },
            { id: "B", text: "Menjalankan TI secara kompeten" },
            { id: "C", text: "Hanya teknis" },
            { id: "D", text: "Menggantikan manajemen" },
        ],
        answerId: "B",
        explanation: "SDM adalah faktor kunci.",
        points: 2,
    },
    {
        id: "t34",
        question: "Continuous improvement berarti …",
        choices: [
            { id: "A", text: "Perubahan sekali" },
            { id: "B", text: "Perbaikan berkelanjutan" },
            { id: "C", text: "Menghentikan layanan" },
            { id: "D", text: "Mengganti sistem total" },
        ],
        answerId: "B",
        explanation: "Perbaikan terus-menerus.",
        points: 2,
    },
    {
        id: "t35",
        question: "Good IT Governance akan menghasilkan …",
        choices: [
            { id: "A", text: "Biaya tinggi" },
            { id: "B", text: "TI bernilai bagi bisnis" },
            { id: "C", text: "Risiko nol" },
            { id: "D", text: "TI teknis saja" },
        ],
        answerId: "B",
        explanation: "Governance yang baik menciptakan nilai.",
        points: 2,
    },
    {
        id: "t36",
        question: "Pengambilan keputusan TI seharusnya …",
        choices: [
            { id: "A", text: "Berdasarkan intuisi" },
            { id: "B", text: "Berbasis data dan kebijakan" },
            { id: "C", text: "Tanpa dokumentasi" },
            { id: "D", text: "Sepihak" },
        ],
        answerId: "B",
        explanation: "Keputusan harus terkontrol.",
        points: 2,
    },
    {
        id: "t37",
        question: "Tata kelola TI membantu organisasi dalam …",
        choices: [
            { id: "A", text: "Pemrograman" },
            { id: "B", text: "Pengendalian risiko" },
            { id: "C", text: "Desain UI" },
            { id: "D", text: "Debugging" },
        ],
        answerId: "B",
        explanation: "Risk control adalah fungsi governance.",
        points: 2,
    },
    {
        id: "t38",
        question: "TI sebagai enabler bisnis berarti …",
        choices: [
            { id: "A", text: "TI sebagai beban" },
            { id: "B", text: "TI mendukung pencapaian tujuan bisnis" },
            { id: "C", text: "TI berdiri sendiri" },
            { id: "D", text: "TI hanya operasional" },
        ],
        answerId: "B",
        explanation: "TI berperan sebagai pendukung strategi.",
        points: 2,
    },
    {
        id: "t39",
        question: "Good governance membutuhkan …",
        choices: [
            { id: "A", text: "Dokumentasi dan kontrol" },
            { id: "B", text: "Teknologi terbaru" },
            { id: "C", text: "Server mahal" },
            { id: "D", text: "Banyak programmer" },
        ],
        answerId: "A",
        explanation: "Kontrol dan dokumentasi penting.",
        points: 2,
    },
    {
        id: "t40",
        question: "Kesimpulan utama tata kelola TI adalah …",
        choices: [
            { id: "A", text: "TI hanya biaya" },
            {
                id: "B",
                text: "TI harus dikelola untuk menciptakan nilai bisnis",
            },
            { id: "C", text: "TI urusan teknis" },
            { id: "D", text: "TI tanpa risiko" },
        ],
        answerId: "B",
        explanation: "Ini inti STSI4402.",
        points: 2,
    },
    {
        id: "t41",
        question: "Tata kelola TI yang buruk dapat menyebabkan …",
        choices: [
            { id: "A", text: "Efisiensi tinggi" },
            { id: "B", text: "Kerugian bisnis" },
            { id: "C", text: "Nilai tambah" },
            { id: "D", text: "Kepatuhan tinggi" },
        ],
        answerId: "B",
        explanation: "Governance buruk berdampak negatif.",
        points: 2,
    },
    {
        id: "t42",
        question: "Kontrol preventif bertujuan untuk …",
        choices: [
            { id: "A", text: "Mendeteksi kesalahan" },
            { id: "B", text: "Mencegah terjadinya kesalahan" },
            { id: "C", text: "Memperbaiki kesalahan" },
            { id: "D", text: "Mengabaikan risiko" },
        ],
        answerId: "B",
        explanation: "Preventif mencegah kejadian.",
        points: 2,
    },
    {
        id: "t43",
        question: "Kontrol detektif bertujuan untuk …",
        choices: [
            { id: "A", text: "Mencegah kesalahan" },
            { id: "B", text: "Mendeteksi kesalahan" },
            { id: "C", text: "Menghilangkan risiko" },
            { id: "D", text: "Mengganti sistem" },
        ],
        answerId: "B",
        explanation: "Detektif menemukan kejadian.",
        points: 2,
    },
    {
        id: "t44",
        question: "Kontrol korektif bertujuan untuk …",
        choices: [
            { id: "A", text: "Memperbaiki kesalahan" },
            { id: "B", text: "Mencegah risiko" },
            { id: "C", text: "Mendeteksi pelanggaran" },
            { id: "D", text: "Audit" },
        ],
        answerId: "A",
        explanation: "Korektif memperbaiki dampak.",
        points: 2,
    },
    {
        id: "t45",
        question: "Governance TI yang baik harus …",
        choices: [
            { id: "A", text: "Terpisah dari bisnis" },
            { id: "B", text: "Selaras dengan strategi bisnis" },
            { id: "C", text: "Fokus teknis" },
            { id: "D", text: "Tidak terdokumentasi" },
        ],
        answerId: "B",
        explanation: "Alignment adalah kunci.",
        points: 2,
    },
    {
        id: "t46",
        question: "Pengukuran kinerja TI penting untuk …",
        choices: [
            { id: "A", text: "Formalitas" },
            { id: "B", text: "Evaluasi dan perbaikan" },
            { id: "C", text: "Menghentikan layanan" },
            { id: "D", text: "Menambah risiko" },
        ],
        answerId: "B",
        explanation: "Tanpa ukur, tidak bisa diperbaiki.",
        points: 2,
    },
    {
        id: "t47",
        question: "Good IT Governance mendukung …",
        choices: [
            { id: "A", text: "Keputusan acak" },
            { id: "B", text: "Pengambilan keputusan yang tepat" },
            { id: "C", text: "Risiko tinggi" },
            { id: "D", text: "TI tanpa arah" },
        ],
        answerId: "B",
        explanation: "Governance mendukung keputusan tepat.",
        points: 2,
    },
    {
        id: "t48",
        question: "Dokumentasi dalam tata kelola TI berfungsi untuk …",
        choices: [
            { id: "A", text: "Administrasi saja" },
            { id: "B", text: "Transparansi dan akuntabilitas" },
            { id: "C", text: "Menghambat kerja" },
            { id: "D", text: "Formalitas" },
        ],
        answerId: "B",
        explanation: "Dokumentasi penting untuk accountability.",
        points: 2,
    },
    {
        id: "t49",
        question: "Evaluasi tata kelola TI dilakukan untuk …",
        choices: [
            { id: "A", text: "Mencari kesalahan personal" },
            { id: "B", text: "Perbaikan berkelanjutan" },
            { id: "C", text: "Menghentikan TI" },
            { id: "D", text: "Audit keuangan" },
        ],
        answerId: "B",
        explanation: "Evaluasi mendukung continuous improvement.",
        points: 2,
    },
    {
        id: "t50",
        question: "Kesimpulan PALING TEPAT tentang tata kelola TI adalah …",
        choices: [
            { id: "A", text: "TI adalah beban biaya" },
            {
                id: "B",
                text: "TI harus dikelola agar memberi nilai dan terkendali",
            },
            { id: "C", text: "TI hanya teknis" },
            { id: "D", text: "TI tanpa risiko" },
        ],
        answerId: "B",
        explanation: "Ini rangkuman seluruh materi STSI4402.",
        points: 2,
    },
];

// SIMULATION_BANK: 10 soal mudah (1 poin tiap soal) — latihan singkat
window.SIMULATION_BANK = [
    {
        id: "sim_g01",
        question: "Apa kepanjangan SLA?",
        choices: [
            { id: "A", text: "Service Level Agreement" },
            { id: "B", text: "System Log Archive" },
            { id: "C", text: "Secure Login Access" },
            { id: "D", text: "Software License Area" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "SLA adalah perjanjian tingkat layanan antara penyedia layanan dan pelanggan.",
    },
    {
        id: "sim_g02",
        question: "Manakah yang merupakan praktik 'least privilege'?",
        choices: [
            {
                id: "A",
                text: "Memberi user hanya akses yang diperlukan untuk tugasnya",
            },
            { id: "B", text: "Memberi semua akses ke user" },
            { id: "C", text: "Menonaktifkan semua akun" },
            { id: "D", text: "Membagikan password" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "Least privilege membatasi akses sehingga mengurangi potensi penyalahgunaan.",
    },
    {
        id: "sim_g03",
        question: "ISO 27001 berhubungan dengan ...",
        choices: [
            { id: "A", text: "Keamanan informasi (ISMS)" },
            { id: "B", text: "Manajemen mutu" },
            { id: "C", text: "Pengembangan software" },
            { id: "D", text: "Desain grafis" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "ISO 27001 menetapkan persyaratan sistem manajemen keamanan informasi.",
    },
    {
        id: "sim_g04",
        question: "RACI membantu organisasi untuk ...",
        choices: [
            {
                id: "A",
                text: "Menetapkan peran dan tanggung jawab pada proses/proyek",
            },
            { id: "B", text: "Menentukan warna dashboard" },
            { id: "C", text: "Melakukan backup saja" },
            { id: "D", text: "Mengingat password" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "RACI memetakan siapa yang Responsible, Accountable, Consulted, dan Informed.",
    },
    {
        id: "sim_g05",
        question: "Business Continuity Plan (BCP) bertujuan untuk ...",
        choices: [
            {
                id: "A",
                text: "Memastikan operasi bisnis tetap berjalan saat gangguan",
            },
            { id: "B", text: "Mempercepat pengembangan fitur" },
            { id: "C", text: "Menambah akses publik" },
            { id: "D", text: "Menghapus data lama" },
        ],
        answerId: "A",
        points: 1,
        time: 60,
        explanation:
            "BCP mempersiapkan proses pemulihan agar bisnis tetap beroperasi selama insiden besar.",
    },
    {
        id: "sim_g06",
        question: "COBIT fokus pada ...",
        choices: [
            { id: "A", text: "Governance & management of enterprise IT" },
            { id: "B", text: "Hanya development software" },
            { id: "C", text: "Hardware procurement" },
            { id: "D", text: "Desain grafis" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "COBIT menyediakan framework praktik terbaik untuk governance dan manajemen TI.",
    },
    {
        id: "sim_g07",
        question: "Kontrol administratif contohnyalah ...",
        choices: [
            { id: "A", text: "Kebijakan keamanan dan pelatihan karyawan" },
            { id: "B", text: "Firewall rules" },
            { id: "C", text: "Enkripsi AES" },
            { id: "D", text: "Load balancing" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "Kontrol administratif adalah kebijakan, prosedur, dan aktivitas manajerial.",
    },
    {
        id: "sim_g08",
        question: "Apa itu 'incident management'?",
        choices: [
            {
                id: "A",
                text: "Proses menangani dan memulihkan insiden layanan TI",
            },
            { id: "B", text: "Membuat desain antarmuka" },
            { id: "C", text: "Menghapus server" },
            { id: "D", text: "Menjadwalkan meeting" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "Incident management fokus pada pemulihan layanan dan minimisasi dampak bisnis.",
    },
    {
        id: "sim_g09",
        question: "Third-party risk management melibatkan ...",
        choices: [
            { id: "A", text: "Due diligence, kontrak, monitoring vendor" },
            { id: "B", text: "Memberi akses penuh ke vendor tanpa audit" },
            { id: "C", text: "Menghapus vendor lama tanpa catatan" },
            { id: "D", text: "Menjadwalkan demo produk" },
        ],
        answerId: "A",
        points: 1,
        time: 60,
        explanation:
            "Manajemen pihak ketiga memastikan vendor memenuhi standar keamanan dan SLA.",
    },
    {
        id: "sim_g10",
        question: "MTTR artinya ...",
        choices: [
            {
                id: "A",
                text: "Mean Time To Repair — rata-rata waktu pemulihan dari kegagalan",
            },
            { id: "B", text: "Maximum Transfer Time Rate" },
            { id: "C", text: "Mean Time To Respond" },
            { id: "D", text: "Minimum Time To Recovery" },
        ],
        answerId: "A",
        points: 1,
        time: 45,
        explanation:
            "MTTR mengukur efektivitas respon dan pemulihan layanan ketika terjadi gangguan.",
    },
];
